package uk.nb.routes.planner.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "PlanetInfo")
public class PlanetInfo {
    private String locationId;
    private String locationName;

    public PlanetInfo() {
    }

    public PlanetInfo(String locationId, String locationName) {
        this.locationId = locationId;
        this.locationName = locationName;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getLocationId() {
        return locationId;
    }

    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    @DynamoDBAttribute
    public String getLocationName() {
        return locationName;
    }

    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }
}
