package uk.nb.routes.planner.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "RouteInfo")
public class RouteInfo {

    private String routeId;
    private String departure;
    private String destination;
    private String departingWeekDay;
    private String leg1;
    private String leg2;
    private String leg3;
    private String leg4;

    public RouteInfo(String routeId) {
        this.routeId = routeId;
    }

    public RouteInfo() {
    }

    public RouteInfo(String routeId, String departure, String destination, String departingWeekDay, String leg1, String leg2, String leg3, String leg4) {
        this.routeId = routeId;
        this.departure = departure;
        this.destination = destination;
        this.departingWeekDay = departingWeekDay;
        this.leg1 = leg1;
        this.leg2 = leg2;
        this.leg3 = leg3;
        this.leg4 = leg4;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getRouteId() {
        return routeId;
    }
    public void setRouteId(String routeId) {
        this.routeId = routeId;
    }

    @DynamoDBAttribute
    public String getDeparture() {
        return departure;
    }

    public void setDeparture(String departure) {
        this.departure = departure;
    }

    @DynamoDBAttribute
    public String getDestination() {
        return destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    @DynamoDBAttribute
    public String getDepartingWeekDay() {
        return departingWeekDay;
    }

    public void setDepartingWeekDay(String departingWeekDay) {
        this.departingWeekDay = departingWeekDay;
    }

    @DynamoDBAttribute
    public String getLeg1() {
        return leg1;
    }

    public void setLeg1(String leg1) {
        this.leg1 = leg1;
    }

    @DynamoDBAttribute
    public String getLeg2() {
        return leg2;
    }

    public void setLeg2(String leg2) {
        this.leg2 = leg2;
    }

    @DynamoDBAttribute
    public String getLeg3() {
        return leg3;
    }

    public void setLeg3(String leg3) {
        this.leg3 = leg3;
    }

    @DynamoDBAttribute
    public String getLeg4() {
        return leg4;
    }

    public void setLeg4(String leg4) {
        this.leg4 = leg4;
    }
}
